pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /Pages

ticketing:
    resource: "@TicketingBundle/Resources/config/routing.yml"
    prefix:   /reservation

app:
    resource: "@TicketingBundle/Controller/"
    type:     annotation
