<?php

namespace Ticketing\TicketingBundle\Repository;

/**
 * commandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindQte($date_commande)
    {
         $query = $this->_em->createQuery('SELECT COUNT(v.nom )from TicketingBundle:Visiteur v JOIN TicketingBundle:Commande c WHERE c.id = v.commande and c.date_commande= :date_commande');
         $query->setParameter('date_commande', $date_commande);
         return $query->getSingleScalarResult();

    }
    public function jourComplet( $date_commande)
    {
        $qb = $this->createQueryBuilder('c');



        $qb ->select('COUNT(v.nom)')
            ->from('TicketingBundle:Visiteur', 'v')
            ->where('c.date_commande = :date_commande')
            ->setParameter('date_commande', $date_commande)
            ->andWhere('c.id=v.commande');

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
