<?php

namespace Ticketing\TicketingBundle\Repository;

/**
 * commandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindQte($date_commande)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('sum(c.qte_place)')
            ->where('c.date_commande = :date_commande')
            ->setParameter('date_commande', $date_commande);

        return
            $qb
                ->getQuery()
                ->getSingleScalarResult();

    }

    public function updatePrix($id, $prix)
    {


        $qB = $this->getEntityManager()->createQueryBuilder();
        $qB->update('TicketingBundle:commande', 'c')
            ->set('c.prix', '?1')
            ->where('c.id = ?2')
            ->setParameter(1, $prix)
            ->setParameter(2, $id);

        return $qB->getQuery();


    }
}
