

ticketing_reservation_home:
    path:     /
    defaults: { _controller: TicketingBundle:Reservation:Commande }

ticketing_reservation_ticket:
    path:     /Ticket
    defaults: { _controller: TicketingBundle:Reservation:Ticket }

ticketing_reservation_paiement:
    path:     /Paiement
    defaults: { _controller: TicketingBundle:Reservation:Paiement }
ticketing_reservation_recapPaiement:
    path:     /Recapitilatif_Paiement
    defaults: { _controller: TicketingBundle:Reservation:RecapPaiement }

