services:
#    ticketing.example:
#        class: Ticketing\TicketingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ticketing.CalculePrix:
        class: Ticketing\TicketingBundle\Service\CalculePrix

    ticketing.CalculePrixTotal:
        class: Ticketing\TicketingBundle\Service\CalculePrixTotal

    ticketing.PaiementStripe:
        class: Ticketing\TicketingBundle\Service\PaiementStripe

    ticketing.EnvoieEmail:
        class: Ticketing\TicketingBundle\Service\EnvoieEmail
        arguments:
           - "@mailer"
           - "@templating"

    ticketing.validator.jourComplet:
            class: Ticketing\TicketingBundle\Validator\JourCompletValidator
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: validator.constraint_validator, alias: jour_complet }
