services:
#    ticketing.example:
#        class: Ticketing\TicketingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    pepert_ticketing.stripe:
        class: Ticketing\TicketingBundle\StripePayment\StripePayment

    ticketing.controle_date:
        class: Ticketing\TicketingBundle\TicketingService\ControleDate