services:
#    ticketing.example:
#        class: Ticketing\TicketingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    ticketing.CalculePrix:
        class: Ticketing\TicketingBundle\Service\CalculePrix

    ticketing.CalculePrixTotal:
        class: Ticketing\TicketingBundle\Service\CalculePrixTotal

    ticketing.PaiementStipe:
        class: Ticketing\TicketingBundle\Service\PaiementStripe